databases:
  - name: useoncemore
    databaseName: useoncemore_db
    user: useoncemore
    region: singapore

services:
  - type: web
    name: useoncemore
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: useoncemore_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

